---

    - name: create virtual host file
      template: 
       src: "/etc/ansible/roles/apache/templates/apache_vhost.conf.j2"
       dest: "/etc/apache2/sites-available/{{ domain }}.conf"
      notify:
      - restart apache2
