---
- hosts: apacheserver
  become: yes
  vars:
   domain: "192.168.56.102"
  vars_files:
     - var.yml
  tasks:
    - name: create virtual port file
      template: 
       src: "/etc/ansible/ports.conf.j2"
       dest: "/etc/apache2/ports.conf"
      notify:
      - restart apache2

    - name: create virtual host file
      template: 
       src: "/etc/ansible/apache_vhost.conf.j2"
       dest: "/etc/apache2/sites-available/{{ domain }}.conf"
      notify:
      - restart apache2

    - name: create vhost directory
      file:
       path: "{{ item.documentroot }}"
       state: "directory"
      with_items:
       - "{{ apache_vhosts }}"
      notify:
      - restart apache2

    - name: a2ensite {{ domain }}
      command: "a2ensite {{ domain }}"
      args:
        creates: "/etc/apache2/sites-available/{{ domain }}.conf"
      notify:
      - restart apache2