---
# Install and configure Apache server
  - hosts: apacheserver
    become: yes 
    vars:
      http_port: 80
      domain: 192.168.56.103
    tasks:
      - name: install apache
        apt:
          name=apache2 
          state=latest 
          update_cache=yes

      - name: enable rewrite_module
        apache2_module: 
          name: rewrite 
          state: present 
        notify:  
         - restart apache2

      - name: apache2 listen to port {{ http_port }}
        lineinfile: 
         dest: /etc/apache2/ports.conf  
         regexp: "^Listen " 
         line: "Listen {{http_port}}" 
         state: present
        notify:
         - restart apache2

      - name: apache2 virtualhost listen to port {{ http_port }}
        lineinfile: 
          dest: /etc/apache2/sites-available/000-default.conf  
          regexp: "^<VirtualHost> "
          line: "<VirtualHost *:{{http_port}}"
          state: present
        notify:
         - restart apache2
      - name: create virtual host file
        template: 
          src: virtualhost.conf 
          dest: /etc/apache2/sites-available/{{ domain }}.conf
      - name: a2ensite {{ domain }}
        command: a2ensite {{ domain }}
        args:
         creates: /etc/apache2/sites-enabled/{{ domain }}.conf
         notify:
          - restart apache2
    handlers:
      - name: restart apache2
        service: name=apache2 state=restarted
...

